config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'
  devise_for :users
  root to: "pages#home"

  # ruta de Escoger un Place y hacer una reserva
  resources :places do
    resources :reservations, only: %i[new create]
    resources :reviews, only: [:new, :create]
  end
  
  # ruta  para que 1 USER pueda ver sus rervaciones
  resources :users do
    resources :reservations, only: :index
  end

  resources :reservations, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :reservations
  validates :city, :area, :price, :description, :address, presence: true
  has_many :reviews, dependent: :destroy
  has_many_attached :photos

  include PgSearch::Model
  pg_search_scope :search_by_places,
  against: [ :city, :area ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :place
  belongs_to :user
  # has_many :users
  # has_many :places
  validate :reservation_date_cannot_be_in_the_past

  def reservation_date_cannot_be_in_the_past
    if date_start.present? && date_finish < Date.today
      errors.add(:date_finish, "can't be in the past")
    end
  end
end

# def reservation_date_cannot_be_in_the_past
#   if date_start.present? && date_finish < Date.today
#     errors.add(:date_finish, "can't be in the past")
#   end
# end

# if deadline > begins_at
#   errors.add(:deadline, 'must be possible')
# end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :place
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reservations, dependent: :destroy
  has_many :places, dependent: :destroy
 # ANDRES MADE ME DO IT validates :first_name, :last_name, :phone_number, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :city])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :city])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
    if params[:query].present?
      sql_query = "area LIKE :query OR city LIKE :query"
      @places = Place.where(sql_query, query: "%#{params[:query]}%")
      @places = Place.first
    else
      @places = Place.all
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %w[show edit update destroy]

  def index
    if params[:query].present?
      sql_query = "city ILIKE :query"
      @places = Place.where(sql_query, query: "%#{params[:query]}%")
    else
      @places = Place.all
    end
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    if @place.save
      redirect_to place_path(@place)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end


  def edit
  end

  def update
    @place.update(place_params)
    redirect_to place_path(@place)
  end

  def destroy
    @place.destroy
    redirect_to root_path
  end

  private
  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:city, :area, :price, :description, :address, photos: [])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @place = place_params
    @reservation = Reservation.new
  end

  def create
    @place = place_params
    @reservation = Reservation.new(reservation_params)
    @reservation.status = "not avaible"
    @reservation.place_id = @place.id
    @reservation.user_id = current_user.id
    if (@reservation.date_finish - @reservation.date_start).zero?
      @reservation.total_price = @place.price
    else
      @reservation.total_price = (@reservation.date_finish - @reservation.date_start) * @place.price
    end
    if @reservation.save
      redirect_to reservation_path(@reservation)
      flash[:notice] = "Reserva creada con éxito"
    else
      render :new, status: :unprocessable_entity
      flash[:notice] = "Error - Revise los datos de la reserva"
    end
  end

  private

  def place_params
    Place.find(params[:place_id])
  end

  def reservation_params
    params.require(:reservation).permit(
      :date_start,
      :date_finish,
      :status,
      :start_time,
      :finish_time,
      :place_id,
      :user_id
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_place, only: %i[new create]
  before_action :set_review, only: %i[edit update destroy]

  def new
    # We need @place in our `simple_form_for`
    @place = Place.find(params[:place_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.place = @place
    if @review.save
    redirect_to place_path(@place)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to place_path(@review.place), status: :see_other
  end

  def edit
  end

  def update
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialRental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- BANNER -->

  <div class="banner_home" style="background-image: url(https://i.pinimg.com/originals/c6/74/57/c67457b78809bb5967e0ee1055e5cbd5.jpg);">
  </div>


<!-- BUSCADOR -->
<!-- EVENTO | FECHA | CIUDAD | ASISTENTES -->

<div class="container py-5 d-flex justify-content-center"> <!-- py espacio arriba y abajo  -->

  <%= form_with url: places_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "¿Dónde?"
    %>
    <%= submit_tag "Buscar", class: "btn btn-outline-dark" %>
  <% end %>
</div>

<!-- CARDS -->
<div class="container pb-3 d-flex">
  <h4>Lo más destacado del mes:</h4>
</div>


<div class="container py-3 d-flex justify-content-center">

  <div class="card-container">
    <% @places.each do |place| %>
    <div class="card-trip">
      <% place.photos.last(1).each do |photo| %>
        <%= cl_image_tag photo.key, crop: :fill %>
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= place.city %></h2>
          <p><%= place.address %></p>
        </div>
        <h2 class="card-trip-pricing"><%= number_to_currency(place.price) %></h2>
      </div>
      <div class="container pb-3">
        <div class="btn btn-outline-dark py3"><%= link_to "Ver más", place_path(place) %> </div>
      </div>
      </div>
    <% end %>
  </div>
</div>


<!-- CARRUSEL -->
<div class="container py-3 d-flex justify-content-center">
  <h4>Encuentra con nosotros el lugar ideal para realizar el evento de tus sueños.</h4>
</div>

<div class="container pb-3 d-flex justify-content-center">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://images.unsplash.com/photo-1623788452350-4c8596ff40bb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="d-block auto" alt="backyard reunion">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1505373877841-8d25f7d46678?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=812&q=80" class="d-block auto" alt="conference">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1566737236500-c8ac43014a67?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="d-block auto" alt="private party">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1514525253161-7a46d19cd819?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" class="d-block auto" alt="concert">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1621112904887-419379ce6824?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=8" class="d-block auto" alt="wedding">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="container d-flex justify-content-center">
  <p>¿Quieres registrar tu local?</p>
</div>
<div class="container d-flex justify-content-center">
  <%= link_to "Empezar", new_place_path, class:"btn btn-outline-dark" %>
</div>

<!-- FOOTER -->


    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
      <div class="footer-copyright">
        Made with <i class="fas fa-heart"></i> by EJF.
      </div>
    </div>

app/views/places/_carrousel.html.erb
<div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel" style="display: flex; justify-content: center;">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img class="img-responsive center-block"
      <% @place.photos.each do |photo| %>
       <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span><i class="glyphicon glyphicon-chevron-left fas fa-chevron-left"></i></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span><i class=" glyphicon glyphicon-chevron-right fas fa-chevron-right"></i></span>
    <span class="sr-only">Próxima</span>
  </a>
</div>

app/views/places/_form.html.erb
<div class="container">

<h2 class="text-center">Alquila tu <strong id="red-word">Local</strong> para tus eventos</h2>

<div id="wrapper">
  <div class="row">
    <div class="text-left form-login">
      <h2 class="text-center"><strong>Ingresa tu Local </strong></h2>
      <br>
      <%= simple_form_for @place do |f| %>
      <%= f.error_notification %>
      <%= f.input :area, placeholder: "Metros cuadrados del local", :label_html => { :class => "label-css"} %>
      <%= f.input :address, label: "Mi local se encuentra ubicado en ", placeholder: "Calle Las Moreas N° 34" %>
      <%= f.input :city, placeholder: "Caracas" %>
      <%= f.input :price, label: "Precio por hora, mínimo 4, en dolares", placeholder: "10" %>
      <%= f.input :description, label: "Descripción", placeholder: "Local amplio, con dos salones principales, recibidor, ubicación céntrica" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
       <%= f.submit "Crear Local", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/places/edit.html.erb
<div class="container-new">
  <div class="container">
    <div id="wrapper">
      <div class="row">
        <div class="text-left form-login">
          <h2 class="text-center"><strong>Edita tu Local </strong></h2>
          <br>
            <div class="places_container">
          <div class="card-trip">
          <% @place.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
            <div class="card-trip-infos">
              <div>
                <h2><%= @place.city %></h2>
                <p><%= @place.address %></p>
              </div>
              <h2 class="card-trip-pricing"><%= @place.price %></h2>
            </div>
          </div>
      </div>

          <%= simple_form_for @place do |f| %>
          <%= f.error_notification %>
          <%= f.input :area, placeholder: "Metros cuadrados del local", :label_html => { :class => "label-css"} %>
          <%= f.input :address, label: "Mi local se encuentra ubicado en ", placeholder: "Calle Las Moreas N° 34" %>
          <%= f.input :city, placeholder: "Caracas" %>
          <%= f.input :price, label: "Precio por hora, en dolares", placeholder: "10" %>
          <%= f.input :description, label: "Descripción", placeholder: "Local amplio, con dos salones principales, recibidor, ubicación céntrica" %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit "Guardar", class: "btn btn-outline-dark" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<div class="container py-3">
  <div class="places_container">
    <% @places.each do |place| %>
    <%#= link_to place_path(place) do %>
      <div class="card-trip">
        <% place.photos.last(1).each do |photo| %>
          <%= cl_image_tag photo.key, crop: :fill %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= place.city %></h2>
            <p><%= place.address %></p>
          </div>
          <h2 class="card-trip-pricing"><%= number_to_currency(place.price)%></h2>
        </div>
        <div class="container pb-3">
        <div class="btn btn-outline-dark"><%= link_to "Ver más", place_path(place) %>
        </div>
        </div>
      </div>
      <% #end %>
    <% end %>
  </div>
</div>

app/views/places/new.html.erb
<div class="container">
<div id="wrapper">
  <div class="row">
    <div class="text-left form-login">
      <h2 class="text-center"><strong>Ingresa tu Local </strong></h2>
      <br>
      <%= simple_form_for @place do |f| %>
      <%= f.error_notification %>
      <%= f.input :area, placeholder: "Metros cuadrados del local", :label_html => { :class => "label-css"} %>
      <%= f.input :address, label: "Mi local se encuentra ubicado en ", placeholder: "Calle Las Moreas N° 34" %>
      <%= f.input :city, placeholder: "Caracas" %>
      <%= f.input :price, label: "Precio por hora, en dolares", placeholder: "10" %>
      <%= f.input :description, label: "Descripción", placeholder: "Local amplio, con dos salones principales, recibidor, ubicación céntrica" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit "Crear Local", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

</div>

</div>

app/views/places/show.html.erb
  <div class="container">
  <div class="places_container">
      <div class="card-trip">
       <% @place.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
       <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= @place.city %></h2>
            <p><%= @place.address %></p>
            <p><%= @place.description %></p>
          </div>
          <h2 class="card-trip-pricing"><%= number_to_currency(@place.price)%></h2>
        </div>
      </div>
  </div>

   <p class="btn btn-basic rounded-pill "><%= link_to 'Regresar', places_path, class: "btn-link-show" %></p>
   <p class="btn btn-basic rounded-pill "><%= link_to 'Reservar', new_place_reservation_path(@place), class: "btn-link-show" %></p>
   
   <% if @place.user == current_user %>
   <p class="btn btn-basic mx-4"><%= link_to 'Edit', edit_place_path(@place), class: "btn-link-show" %></p>
   <p class="btn btn-destroy"><%= link_to 'Destroy', @place, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn-link-show" %></p>
  <%end%>

  <p><strong>Reseñas</strong></p>
  <ul class="list-group">
    <% @place.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %></li>
    <% end %>
  </ul>
</div>

app/views/reservations/index.html.erb
<div class="container bg-white p-3">
  <div>
    <h1 class="text-start py-2">Reservación del cliente:</h1>
      <h3 class="text-start py-3"><strong>
      <%= current_user.first_name %> <%= current_user.last_name %>
      </strong></h3><br>
    <% @reservations.each do |reservation| %>
  <div class="card mb-3" style="max-width: 680px;">
    <div class="row g-0">
      <div class="col-md-4 p-2">
        <% reservation.place.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 150, width: 225, crop: :pad %>
        <% end %>
      </div>
      <div class="col-md-6 x-2">
        <div class="card-body">
          <h6 class="card-title"> <%= reservation.place.address %>, <%= reservation.place.city %></h6>
          <p> Información básica del local</p>
          <p> Precio: <%= number_to_currency(reservation.total_price) %></p>
          <%= link_to "Más detalle", reservation_path(reservation) %>
        </div>
      </div>
    </div>
  </div>
    <% end %>
    <%# Boton  %>
    <div class="container col-3 mb-5 py-5">
      <%= link_to "Ver otros locales", places_path, class: "btn-outline-dark" %>
    </div>
    <%# fin Boton  %>
</div>

app/views/reservations/new.html.erb
<div class="container d-flex justify-content-center bg-white">
  <div class="row d-flex justify-content-center p-4">
    <h1>Nueva Reserva:</h1><br>
    <div class="col-md-6 d-flex justify-content-center bg-white">
        <div class="card mb-3" style="max-width: 740px;">
          <div class="card-body mt-3">
            <div class="col-md-4">
              <% @place.photos.each do |photo| %>
                <%= cl_image_tag photo.key, height: 350, width: 500, crop: :pad %>
              <% end %>
            </div>
            <div class="col-md-4 d-flex flex-column">
              <div class="card-body">
              <h5 class="card-title"> <strong><%= @place.city %>, <%= @place.address %></strong></h5><br>
              <p class="card-text">Información del local por completar.</p>
              <p class="card-text">Precio: <%= number_to_currency(@place.price) %> </p>
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="col-md-4 border bg-white"><br>
      <%= simple_form_for [@place, @reservation] do |f| %>
        <%= f.input :date_start%>
        <%= f.input :date_finish %>
        <%= f.input :start_time %>
        <%= f.input :finish_time %>
        <%= f.submit "Crear Reserva", class: "btn btn-success" %>
          <div class= "btn btn-danger" class="col-4">
            <%= link_to "Cancelar Reserva", places_path %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container bg-white">
  <div class="mb-2 mt-1">
    <h1 class="text-center py-3"> <strong> <%= @reservation.place.address %>, <%= @reservation.place.city %></strong></h1>
  </div>
  <div class="row  mt-1 mb-3 ">
    <div class="col">
      <% @reservation.place.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 450, width: 750, crop: :pad %>
      <% end %>
    </div>
    <div class="col py-5">
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      <%#= @resreservation.place.descpcion %> </p>
      <p class="card-text">:::FECHA RESERVA:::</p>
      <p class="card-text">Desde: <%= @reservation.date_start %></p>
      <p class="card-text">Hasta: <%= @reservation.date_start %></p><br>
      <p class="card-text"><strong> Precio: <%= number_to_currency(@reservation.total_price) %></strong></p>
    </div><br>
    <div class= "btn btn-light mt-3" class="col-4">
      <%= link_to "Escoger Nuevo Local", places_path %>
    </div>
    <div class= "btn btn-light mb-2 mt-1" class="col-4">
      <%= link_to "Mis Reservas", user_reservations_path(current_user.id) %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Nueva Reseña</h1>
<%= simple_form_for [@place, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Enviar Reseña", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://i.pinimg.com/originals/1e/59/d8/1e59d81cfb6a9d87dee97422b4c084fb.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mensajes", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%#= MODIFIQUE LA RUTA PARA QUE EL USER EDITE SU PERFIL %>
              <%= link_to "Editar Perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%#= MODIFIQUE LA RUTA PARA QUE EL USER VEA SUS RESERVAS -user_reservations_path-%>
              <%= link_to "Mis reservas", user_reservations_path(current_user), class: "dropdown-item" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>